version: '3.8'

services:
  api:
    build: .
    environment:
      APP_PORT: 80
    ports:
      - '80:80'
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '1GB'
    network_mode: 'host'