version: '3.8'

services:
  api01: &api
    build: .
    environment:
      APP_PORT: 8080
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '1GB'
    network_mode: 'host'

  api02:
    <<: *api
    environment:
      APP_PORT: 8081

  nginx:
    image: nginx:1.25.3-alpine
    ports:
      - '80:80'
    volumes:
      - .docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    network_mode: 'host'
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '1GB'