version: '3.8'

services:

  api:
    build: .
    environment:
      APP_PORT: 80
      CLUSTER_WORKERS: 4
    network_mode: 'host'
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '2GB'
  